# Generated by Django 5.1.1 on 2024-10-04 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionexamen',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examen',
            name='usuarios',
            field=models.ManyToManyField(through='dashboard_users.InscripcionExamen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='enunciado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_relacionadas', to='dashboard_users.pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='dashboard_users.modulo'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='dashboard_users.pregunta'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='dashboard_users.tipoexamen'),
        ),
        migrations.AddField(
            model_name='examen',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='dashboard_users.tipoexamen'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_users.examen'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='preguntas',
            field=models.ManyToManyField(to='dashboard_users.pregunta'),
        ),
        migrations.AddField(
            model_name='userexam',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
