# Generated by Django 5.1.1 on 2024-10-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_users', '0004_examen_preguntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='enunciado',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='identificador_de_grupo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
